##### Copyright 2020 The TensorFlow Authors.

In [1]:
#@title Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

<table class="tfo-notebook-buttons" align="left">
  <td>
    <a target="_blank" href="https://www.tensorflow.org/text/tutorials/word2vec"><img src="https://www.tensorflow.org/images/tf_logo_32px.png" />View on TensorFlow.org</a>
  </td>
  <td>
    <a target="_blank" href="https://colab.research.google.com/github/tensorflow/text/blob/master/docs/tutorials/word2vec.ipynb"><img src="https://www.tensorflow.org/images/colab_logo_32px.png" />Run in Google Colab</a>
  </td>
  <td>
    <a target="_blank" href="https://github.com/tensorflow/text/blob/master/docs/tutorials/word2vec.ipynb"><img src="https://www.tensorflow.org/images/GitHub-Mark-32px.png" />View on GitHub</a>
  </td>
  <td>
    <a href="https://storage.googleapis.com/tensorflow_docs/text/docs/tutorials/word2vec.ipynb"><img src="https://www.tensorflow.org/images/download_logo_32px.png" />Download notebook</a>
  </td>
</table>

# word2vec

word2vec is not a singular algorithm, rather, it is a family of model architectures and optimizations that can be used to learn word embeddings from large datasets. Embeddings learned through word2vec have proven to be successful on a variety of downstream natural language processing tasks.

Note: This tutorial is based on [Efficient estimation of word representations in vector space](https://arxiv.org/pdf/1301.3781.pdf) and [Distributed representations of words and phrases and their compositionality](https://papers.nips.cc/paper/5021-distributed-representations-of-words-and-phrases-and-their-compositionality.pdf). It is not an exact implementation of the papers. Rather, it is intended to illustrate the key ideas.

These papers proposed two methods for learning representations of words:

*   **Continuous bag-of-words model**: predicts the middle word based on surrounding context words. The context consists of a few words before and after the current (middle) word. This architecture is called a bag-of-words model as the order of words in the context is not important.
*   **Continuous skip-gram model**: predicts words within a certain range before and after the current word in the same sentence. A worked example of this is given below.

You'll use the skip-gram approach in this tutorial. First, you'll explore skip-grams and other concepts using a single sentence for illustration. Next, you'll train your own word2vec model on a small dataset. This tutorial also contains code to export the trained embeddings and visualize them in the [TensorFlow Embedding Projector](http://projector.tensorflow.org/).


## Skip-gram and negative sampling 

While a bag-of-words model predicts a word given the neighboring context, a skip-gram model predicts the context (or neighbors) of a word, given the word itself. The model is trained on skip-grams, which are n-grams that allow tokens to be skipped (see the diagram below for an example). The context of a word can be represented through a set of skip-gram pairs of `(target_word, context_word)` where `context_word` appears in the neighboring context of `target_word`. 

Consider the following sentence of eight words:

> The wide road shimmered in the hot sun.

The context words for each of the 8 words of this sentence are defined by a window size. The window size determines the span of words on either side of a `target_word` that can be considered a `context word`. Below is a table of skip-grams for target words based on different window sizes.

Note: For this tutorial, a window size of `n` implies n words on each side with a total window span of 2*n+1 words across a word.

![word2vec_skipgrams](https://tensorflow.org/text/tutorials/images/word2vec_skipgram.png)

The training objective of the skip-gram model is to maximize the probability of predicting context words given the target word. For a sequence of words *w<sub>1</sub>, w<sub>2</sub>, ... w<sub>T</sub>*, the objective can be written as the average log probability

![word2vec_skipgram_objective](https://tensorflow.org/text/tutorials/images/word2vec_skipgram_objective.png)

where `c` is the size of the training context. The basic skip-gram formulation defines this probability using the softmax function.

![word2vec_full_softmax](https://tensorflow.org/text/tutorials/images/word2vec_full_softmax.png)

where *v* and *v<sup>'<sup>* are target and context vector representations of words and *W* is vocabulary size. 

Computing the denominator of this formulation involves performing a full softmax over the entire vocabulary words, which are often large (10<sup>5</sup>-10<sup>7</sup>) terms.

The [noise contrastive estimation](https://www.tensorflow.org/api_docs/python/tf/nn/nce_loss) (NCE) loss function is an efficient approximation for a full softmax. With an objective to learn word embeddings instead of modeling the word distribution, the NCE loss can be [simplified](https://papers.nips.cc/paper/5021-distributed-representations-of-words-and-phrases-and-their-compositionality.pdf) to use negative sampling. 

The simplified negative sampling objective for a target word is to distinguish  the context word from `num_ns` negative samples drawn from noise distribution *P<sub>n</sub>(w)* of words. More precisely, an efficient approximation of full softmax over the vocabulary is, for a skip-gram pair, to pose the loss for a target word as a classification problem between the context word and `num_ns` negative samples. 

A negative sample is defined as a `(target_word, context_word)` pair such that the `context_word` does not appear in the `window_size` neighborhood of the `target_word`. For the example sentence, these are a few potential negative samples (when `window_size` is `2`).

```
(hot, shimmered)
(wide, hot)
(wide, sun)
```

In the next section, you'll generate skip-grams and negative samples for a single sentence. You'll also learn about subsampling techniques and train a classification model for positive and negative training examples later in the tutorial.

## Setup

In [2]:
import io
import re
import string
import tqdm

import numpy as np

import tensorflow as tf
from tensorflow.keras import layers

2024-02-22 14:53:59.062958: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2024-02-22 14:53:59.134703: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-02-22 14:53:59.134743: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-02-22 14:53:59.139028: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-02-22 14:53:59.156155: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2024-02-22 14:53:59.156671: I tensorflow/core/platform/cpu_feature_guard.cc:1

In [3]:
# Load the TensorBoard notebook extension
%load_ext tensorboard

In [4]:
SEED = 42
AUTOTUNE = tf.data.AUTOTUNE

### Vectorize an example sentence

Consider the following sentence:

> The wide road shimmered in the hot sun.

Tokenize the sentence:

In [5]:
sentence = "The wide road shimmered in the hot sun"
tokens = list(sentence.lower().split())
print(len(tokens))

8


Create a vocabulary to save mappings from tokens to integer indices:

In [6]:
vocab, index = {}, 1  # start indexing from 1
vocab['<pad>'] = 0  # add a padding token
for token in tokens:
  if token not in vocab:
    vocab[token] = index
    index += 1
vocab_size = len(vocab)
print(vocab)

{'<pad>': 0, 'the': 1, 'wide': 2, 'road': 3, 'shimmered': 4, 'in': 5, 'hot': 6, 'sun': 7}


Create an inverse vocabulary to save mappings from integer indices to tokens:

In [7]:
inverse_vocab = {index: token for token, index in vocab.items()}
print(inverse_vocab)

{0: '<pad>', 1: 'the', 2: 'wide', 3: 'road', 4: 'shimmered', 5: 'in', 6: 'hot', 7: 'sun'}


Vectorize your sentence:

In [8]:
example_sequence = [vocab[word] for word in tokens]
print(example_sequence)

[1, 2, 3, 4, 5, 1, 6, 7]


### Generate skip-grams from one sentence

The `tf.keras.preprocessing.sequence` module provides useful functions that simplify data preparation for word2vec. You can use the `tf.keras.preprocessing.sequence.skipgrams` to generate skip-gram pairs from the `example_sequence` with a given `window_size` from tokens in the range `[0, vocab_size)`.

Note: `negative_samples` is set to `0` here, as batching negative samples generated by this function requires a bit of code. You will use another function to perform negative sampling in the next section.

In [9]:
window_size = 2
positive_skip_grams, _ = tf.keras.preprocessing.sequence.skipgrams(
      example_sequence,
      vocabulary_size=vocab_size,
      window_size=window_size,
      negative_samples=0)
print(len(positive_skip_grams))

26


Print a few positive skip-grams:

In [10]:
for target, context in positive_skip_grams[:5]:
  print(f"({target}, {context}): ({inverse_vocab[target]}, {inverse_vocab[context]})")

(3, 5): (road, in)
(1, 4): (the, shimmered)
(5, 4): (in, shimmered)
(7, 1): (sun, the)
(2, 1): (wide, the)


### Negative sampling for one skip-gram 

The `skipgrams` function returns all positive skip-gram pairs by sliding over a given window span. To produce additional skip-gram pairs that would serve as negative samples for training, you need to sample random words from the vocabulary. Use the `tf.random.log_uniform_candidate_sampler` function to sample `num_ns` number of negative samples for a given target word in a window. You can call the function on one skip-grams's target word and pass the context word as true class to exclude it from being sampled.


Key point: `num_ns` (the number of negative samples per a positive context word) in the `[5, 20]` range is [shown to work](https://papers.nips.cc/paper/5021-distributed-representations-of-words-and-phrases-and-their-compositionality.pdf) best for smaller datasets, while `num_ns` in the `[2, 5]` range suffices for larger datasets.

In [11]:
# Get target and context words for one positive skip-gram.
target_word, context_word = positive_skip_grams[0]

# Set the number of negative samples per positive context.
num_ns = 4

context_class = tf.reshape(tf.constant(context_word, dtype="int64"), (1, 1))
negative_sampling_candidates, _, _ = tf.random.log_uniform_candidate_sampler(
    true_classes=context_class,  # class that should be sampled as 'positive'
    num_true=1,  # each positive skip-gram has 1 positive context class
    num_sampled=num_ns,  # number of negative context words to sample
    unique=True,  # all the negative samples should be unique
    range_max=vocab_size,  # pick index of the samples from [0, vocab_size]
    seed=SEED,  # seed for reproducibility
    name="negative_sampling"  # name of this operation
)
print(negative_sampling_candidates)
print([inverse_vocab[index.numpy()] for index in negative_sampling_candidates])

tf.Tensor([2 1 4 3], shape=(4,), dtype=int64)
['wide', 'the', 'shimmered', 'road']


### Construct one training example

For a given positive `(target_word, context_word)` skip-gram, you now also have `num_ns` negative sampled context words that do not appear in the window size neighborhood of `target_word`. Batch the `1` positive `context_word` and `num_ns` negative context words into one tensor. This produces a set of positive skip-grams (labeled as `1`) and negative samples (labeled as `0`) for each target word.

In [12]:
# Reduce a dimension so you can use concatenation (in the next step).
squeezed_context_class = tf.squeeze(context_class, 1)

# Concatenate a positive context word with negative sampled words.
context = tf.concat([squeezed_context_class, negative_sampling_candidates], 0)

# Label the first context word as `1` (positive) followed by `num_ns` `0`s (negative).
label = tf.constant([1] + [0]*num_ns, dtype="int64")
target = target_word


Check out the context and the corresponding labels for the target word from the skip-gram example above:

In [13]:
print(f"target_index    : {target}")
print(f"target_word     : {inverse_vocab[target_word]}")
print(f"context_indices : {context}")
print(f"context_words   : {[inverse_vocab[c.numpy()] for c in context]}")
print(f"label           : {label}")

target_index    : 3
target_word     : road
context_indices : [5 2 1 4 3]
context_words   : ['in', 'wide', 'the', 'shimmered', 'road']
label           : [1 0 0 0 0]


A tuple of `(target, context, label)` tensors constitutes one training example for training your skip-gram negative sampling word2vec model. Notice that the target is of shape `(1,)` while the context and label are of shape `(1+num_ns,)`

In [14]:
print("target  :", target)
print("context :", context)
print("label   :", label)

target  : 3
context : tf.Tensor([5 2 1 4 3], shape=(5,), dtype=int64)
label   : tf.Tensor([1 0 0 0 0], shape=(5,), dtype=int64)


### Summary

This diagram summarizes the procedure of generating a training example from a sentence:


![word2vec_negative_sampling](https://tensorflow.org/text/tutorials/images/word2vec_negative_sampling.png)

Notice that the words `temperature` and `code` are not part of the input sentence. They belong to the vocabulary like certain other indices used in the diagram above.

## Compile all steps into one function


### Skip-gram sampling table 

A large dataset means larger vocabulary with higher number of more frequent words such as stopwords. Training examples obtained from sampling commonly occurring words (such as `the`, `is`, `on`) don't add much useful information  for the model to learn from. [Mikolov et al.](https://papers.nips.cc/paper/5021-distributed-representations-of-words-and-phrases-and-their-compositionality.pdf) suggest subsampling of frequent words as a helpful practice to improve embedding quality. 

The `tf.keras.preprocessing.sequence.skipgrams` function accepts a sampling table argument to encode probabilities of sampling any token. You can use the `tf.keras.preprocessing.sequence.make_sampling_table` to  generate a word-frequency rank based probabilistic sampling table and pass it to the `skipgrams` function. Inspect the sampling probabilities for a `vocab_size` of 10.

In [15]:
sampling_table = tf.keras.preprocessing.sequence.make_sampling_table(size=10)
print(sampling_table)

[0.00315225 0.00315225 0.00547597 0.00741556 0.00912817 0.01068435
 0.01212381 0.01347162 0.01474487 0.0159558 ]


`sampling_table[i]` denotes the probability of sampling the i-th most common word in a dataset. The function assumes a [Zipf's distribution](https://en.wikipedia.org/wiki/Zipf%27s_law) of the word frequencies for sampling.

Key point: The `tf.random.log_uniform_candidate_sampler` already assumes that the vocabulary frequency follows a log-uniform (Zipf's) distribution. Using these distribution weighted sampling also helps approximate the Noise Contrastive Estimation (NCE) loss with simpler loss functions for training a negative sampling objective.

### Generate training data

Compile all the steps described above into a function that can be called on a list of vectorized sentences obtained from any text dataset. Notice that the sampling table is built before sampling skip-gram word pairs. You will use this function in the later sections.

In [16]:
# Generates skip-gram pairs with negative sampling for a list of sequences
# (int-encoded sentences) based on window size, number of negative samples
# and vocabulary size.
def generate_training_data(sequences, window_size, num_ns, vocab_size, seed):
  # Elements of each training example are appended to these lists.
  targets, contexts, labels = [], [], []

  # Build the sampling table for `vocab_size` tokens.
  sampling_table = tf.keras.preprocessing.sequence.make_sampling_table(vocab_size)

  # Iterate over all sequences (sentences) in the dataset.
  for sequence in tqdm.tqdm(sequences):

    # Generate positive skip-gram pairs for a sequence (sentence).
    positive_skip_grams, _ = tf.keras.preprocessing.sequence.skipgrams(
          sequence,
          vocabulary_size=vocab_size,
          sampling_table=sampling_table,
          window_size=window_size,
          negative_samples=0)

    # Iterate over each positive skip-gram pair to produce training examples
    # with a positive context word and negative samples.
    for target_word, context_word in positive_skip_grams:
      context_class = tf.expand_dims(
          tf.constant([context_word], dtype="int64"), 1)
      negative_sampling_candidates, _, _ = tf.random.log_uniform_candidate_sampler(
          true_classes=context_class,
          num_true=1,
          num_sampled=num_ns,
          unique=True,
          range_max=vocab_size,
          seed=seed,
          name="negative_sampling")

      # Build context and label vectors (for one target word)
      context = tf.concat([tf.squeeze(context_class,1), negative_sampling_candidates], 0)
      label = tf.constant([1] + [0]*num_ns, dtype="int64")

      # Append each element from the training example to global lists.
      targets.append(target_word)
      contexts.append(context)
      labels.append(label)

  return targets, contexts, labels

## Prepare training data for word2vec

With an understanding of how to work with one sentence for a skip-gram negative sampling based word2vec model, you can proceed to generate training examples from a larger list of sentences!

### Download text corpus


You will use a text file of Shakespeare's writing for this tutorial. Change the following line to run this code on your own data.

In [17]:
path_to_file = tf.keras.utils.get_file('shakespeare.txt', 'https://storage.googleapis.com/download.tensorflow.org/data/shakespeare.txt')

1115394/1115394 [==============================] - 0s 0us/step


Read the text from the file and print the first few lines: 

In [18]:
with open(path_to_file) as f:
  lines = f.read().splitlines()
for line in lines[:20]:
  print(line)

First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
You are all resolved rather to die than to famish?

All:
Resolved. resolved.

First Citizen:
First, you know Caius Marcius is chief enemy to the people.

All:
We know't, we know't.

First Citizen:
Let us kill him, and we'll have corn at our own price.


Use the non empty lines to construct a `tf.data.TextLineDataset` object for the next steps:

In [19]:
text_ds = tf.data.TextLineDataset(path_to_file).filter(lambda x: tf.cast(tf.strings.length(x), bool))

### Vectorize sentences from the corpus

You can use the `TextVectorization` layer to vectorize sentences from the corpus. Learn more about using this layer in this [Text classification](https://www.tensorflow.org/tutorials/keras/text_classification) tutorial. Notice from the first few sentences above that the text needs to be in one case and punctuation needs to be removed. To do this, define a `custom_standardization function` that can be used in the TextVectorization layer.

In [20]:
# Now, create a custom standardization function to lowercase the text and
# remove punctuation.
def custom_standardization(input_data):
  lowercase = tf.strings.lower(input_data)
  return tf.strings.regex_replace(lowercase,
                                  '[%s]' % re.escape(string.punctuation), '')


# Define the vocabulary size and the number of words in a sequence.
vocab_size = 4096
sequence_length = 10

# Use the `TextVectorization` layer to normalize, split, and map strings to
# integers. Set the `output_sequence_length` length to pad all samples to the
# same length.
vectorize_layer = layers.TextVectorization(
    standardize=custom_standardization,
    max_tokens=vocab_size,
    output_mode='int',
    output_sequence_length=sequence_length)

Call `TextVectorization.adapt` on the text dataset to create vocabulary.


In [21]:
vectorize_layer.adapt(text_ds.batch(1024))

Once the state of the layer has been adapted to represent the text corpus, the vocabulary can be accessed with `TextVectorization.get_vocabulary`. This function returns a list of all vocabulary tokens sorted (descending) by their frequency.

In [22]:
# Save the created vocabulary for reference.
inverse_vocab = vectorize_layer.get_vocabulary()
print(inverse_vocab[:20])

['', '[UNK]', 'the', 'and', 'to', 'i', 'of', 'you', 'my', 'a', 'that', 'in', 'is', 'not', 'for', 'with', 'me', 'it', 'be', 'your']


The `vectorize_layer` can now be used to generate vectors for each element in the `text_ds` (a `tf.data.Dataset`). Apply `Dataset.batch`, `Dataset.prefetch`, `Dataset.map`, and `Dataset.unbatch`.

In [23]:
# Vectorize the data in text_ds.
text_vector_ds = text_ds.batch(1024).prefetch(AUTOTUNE).map(vectorize_layer).unbatch()

### Obtain sequences from the dataset

You now have a `tf.data.Dataset` of integer encoded sentences. To prepare the dataset for training a word2vec model, flatten the dataset into a list of sentence vector sequences. This step is required as you would iterate over each sentence in the dataset to produce positive and negative examples.

Note: Since the `generate_training_data()` defined earlier uses non-TensorFlow Python/NumPy functions, you could also use a `tf.py_function` or `tf.numpy_function` with `tf.data.Dataset.map`.

In [24]:
sequences = list(text_vector_ds.as_numpy_iterator())
print(len(sequences))

32777


Inspect a few examples from `sequences`:

In [25]:
for seq in sequences[:5]:
  print(f"{seq} => {[inverse_vocab[i] for i in seq]}")

[ 89 270   0   0   0   0   0   0   0   0] => ['first', 'citizen', '', '', '', '', '', '', '', '']
[138  36 982 144 673 125  16 106   0   0] => ['before', 'we', 'proceed', 'any', 'further', 'hear', 'me', 'speak', '', '']
[34  0  0  0  0  0  0  0  0  0] => ['all', '', '', '', '', '', '', '', '', '']
[106 106   0   0   0   0   0   0   0   0] => ['speak', 'speak', '', '', '', '', '', '', '', '']
[ 89 270   0   0   0   0   0   0   0   0] => ['first', 'citizen', '', '', '', '', '', '', '', '']


In [26]:
sequences

[array([ 89, 270,   0,   0,   0,   0,   0,   0,   0,   0]),
 array([138,  36, 982, 144, 673, 125,  16, 106,   0,   0]),
 array([34,  0,  0,  0,  0,  0,  0,  0,  0,  0]),
 array([106, 106,   0,   0,   0,   0,   0,   0,   0,   0]),
 array([ 89, 270,   0,   0,   0,   0,   0,   0,   0,   0]),
 array([   7,   41,   34, 1286,  344,    4,  200,   64,    4, 3690]),
 array([34,  0,  0,  0,  0,  0,  0,  0,  0,  0]),
 array([1286, 1286,    0,    0,    0,    0,    0,    0,    0,    0]),
 array([ 89, 270,   0,   0,   0,   0,   0,   0,   0,   0]),
 array([  89,    7,   93, 1187,  225,   12, 2442,  592,    4,    2]),
 array([34,  0,  0,  0,  0,  0,  0,  0,  0,  0]),
 array([  36, 2655,   36, 2655,    0,    0,    0,    0,    0,    0]),
 array([ 89, 270,   0,   0,   0,   0,   0,   0,   0,   0]),
 array([  72,   79,  506,   27,    3,   56,   24, 1390,   57,   40]),
 array([644,   9,   1,   0,   0,   0,   0,   0,   0,   0]),
 array([34,  0,  0,  0,  0,  0,  0,  0,  0,  0]),
 array([  32,   54, 2863,  885

### Generate training examples from sequences

`sequences` is now a list of int encoded sentences. Just call the `generate_training_data` function defined earlier to generate training examples for the word2vec model. To recap, the function iterates over each word from each sequence to collect positive and negative context words. Length of target, contexts and labels should be the same, representing the total number of training examples.

In [26]:
targets, contexts, labels = generate_training_data(
    sequences=sequences,
    window_size=2,
    num_ns=4,
    vocab_size=vocab_size,
    seed=SEED)

targets = np.array(targets)
contexts = np.array(contexts)
labels = np.array(labels)

print('\n')
print(f"targets.shape: {targets.shape}")
print(f"contexts.shape: {contexts.shape}")
print(f"labels.shape: {labels.shape}")



  0%|          | 0/32777 [00:00<?, ?it/s]


  0%|          | 105/32777 [00:00<00:32, 1017.19it/s]


  1%|          | 207/32777 [00:00<00:34, 932.24it/s] 


  1%|          | 301/32777 [00:00<00:34, 928.51it/s]


  1%|          | 395/32777 [00:00<00:36, 897.42it/s]


  1%|▏         | 485/32777 [00:00<00:38, 848.26it/s]


  2%|▏         | 597/32777 [00:00<00:34, 919.57it/s]


  2%|▏         | 690/32777 [00:00<00:36, 873.54it/s]


  2%|▏         | 778/32777 [00:00<00:37, 849.03it/s]


  3%|▎         | 869/32777 [00:00<00:36, 865.18it/s]


  3%|▎         | 958/32777 [00:01<00:36, 870.11it/s]


  3%|▎         | 1051/32777 [00:01<00:35, 887.35it/s]


  4%|▎         | 1157/32777 [00:01<00:33, 930.98it/s]


  4%|▍         | 1253/32777 [00:01<00:34, 921.85it/s]


  4%|▍         | 1370/32777 [00:01<00:31, 993.70it/s]


  4%|▍         | 1470/32777 [00:01<00:32, 948.76it/s]


  5%|▍         | 1566/32777 [00:01<00:33, 938.85it/s]


  5%|▌         | 1668/32777 [00:01<00:32, 958.53it/s]


  5%|▌         | 1765/32777 [00:01<00:34, 891.08it/s]


  6%|▌         | 1871/32777 [00:02<00:33, 935.23it/s]


  6%|▌         | 1985/32777 [00:02<00:31, 989.75it/s]


  6%|▋         | 2086/32777 [00:02<00:32, 953.27it/s]


  7%|▋         | 2208/32777 [00:02<00:29, 1027.19it/s]


  7%|▋         | 2312/32777 [00:02<00:30, 986.35it/s] 


  7%|▋         | 2429/32777 [00:02<00:29, 1029.71it/s]


  8%|▊         | 2552/32777 [00:02<00:27, 1080.33it/s]


  8%|▊         | 2662/32777 [00:02<00:27, 1085.69it/s]


  8%|▊         | 2772/32777 [00:02<00:29, 1028.97it/s]


  9%|▉         | 2876/32777 [00:03<00:29, 1014.02it/s]


  9%|▉         | 2999/32777 [00:03<00:28, 1063.17it/s]


  9%|▉         | 3106/32777 [00:03<00:29, 1004.05it/s]


 10%|▉         | 3219/32777 [00:03<00:28, 1026.99it/s]


 10%|█         | 3323/32777 [00:03<00:30, 957.70it/s] 


 11%|█         | 3448/32777 [00:03<00:28, 1036.83it/s]


 11%|█         | 3554/32777 [00:03<00:30, 949.98it/s] 


 11%|█         | 3653/32777 [00:03<00:30, 954.75it/s]


 12%|█▏        | 3785/32777 [00:03<00:27, 1046.18it/s]


 12%|█▏        | 3892/32777 [00:04<00:27, 1041.02it/s]


 12%|█▏        | 3998/32777 [00:04<00:30, 946.44it/s] 


 12%|█▏        | 4095/32777 [00:04<00:31, 909.01it/s]


 13%|█▎        | 4201/32777 [00:04<00:30, 945.29it/s]


 13%|█▎        | 4298/32777 [00:04<00:32, 869.64it/s]


 13%|█▎        | 4393/32777 [00:04<00:31, 889.04it/s]


 14%|█▎        | 4484/32777 [00:04<00:36, 764.97it/s]


 14%|█▍        | 4590/32777 [00:04<00:34, 827.08it/s]


 14%|█▍        | 4682/32777 [00:04<00:33, 848.84it/s]


 15%|█▍        | 4804/32777 [00:05<00:29, 944.96it/s]


 15%|█▍        | 4902/32777 [00:05<00:29, 950.06it/s]


 15%|█▌        | 5000/32777 [00:05<00:30, 917.78it/s]


 16%|█▌        | 5094/32777 [00:05<00:31, 868.98it/s]


 16%|█▌        | 5183/32777 [00:05<00:31, 864.12it/s]


 16%|█▌        | 5296/32777 [00:05<00:29, 930.49it/s]


 16%|█▋        | 5391/32777 [00:05<00:29, 924.73it/s]


 17%|█▋        | 5487/32777 [00:05<00:29, 925.93it/s]


 17%|█▋        | 5581/32777 [00:05<00:31, 876.56it/s]


 17%|█▋        | 5670/32777 [00:06<00:31, 870.96it/s]


 18%|█▊        | 5758/32777 [00:06<00:31, 866.63it/s]


 18%|█▊        | 5847/32777 [00:06<00:30, 871.16it/s]


 18%|█▊        | 5935/32777 [00:06<00:33, 790.86it/s]


 18%|█▊        | 6028/32777 [00:06<00:32, 826.44it/s]


 19%|█▊        | 6121/32777 [00:06<00:31, 852.91it/s]


 19%|█▉        | 6224/32777 [00:06<00:29, 901.11it/s]


 19%|█▉        | 6326/32777 [00:06<00:28, 927.55it/s]


 20%|█▉        | 6420/32777 [00:06<00:28, 923.80it/s]


 20%|█▉        | 6513/32777 [00:07<00:30, 861.31it/s]


 20%|██        | 6601/32777 [00:07<00:31, 824.31it/s]


 20%|██        | 6697/32777 [00:07<00:30, 856.57it/s]


 21%|██        | 6784/32777 [00:07<00:30, 845.64it/s]


 21%|██        | 6871/32777 [00:07<00:30, 850.24it/s]


 21%|██▏       | 6996/32777 [00:07<00:26, 963.84it/s]


 22%|██▏       | 7110/32777 [00:07<00:25, 1005.53it/s]


 22%|██▏       | 7212/32777 [00:07<00:28, 893.50it/s] 


 22%|██▏       | 7316/32777 [00:07<00:27, 930.85it/s]


 23%|██▎       | 7412/32777 [00:08<00:27, 917.49it/s]


 23%|██▎       | 7506/32777 [00:08<00:28, 897.05it/s]


 23%|██▎       | 7597/32777 [00:08<00:31, 792.49it/s]


 23%|██▎       | 7679/32777 [00:08<00:33, 745.42it/s]


 24%|██▎       | 7768/32777 [00:08<00:32, 779.74it/s]


 24%|██▍       | 7852/32777 [00:08<00:31, 793.76it/s]


 24%|██▍       | 7959/32777 [00:08<00:28, 869.45it/s]


 25%|██▍       | 8048/32777 [00:08<00:28, 866.68it/s]


 25%|██▍       | 8140/32777 [00:08<00:27, 880.33it/s]


 25%|██▌       | 8246/32777 [00:09<00:26, 931.56it/s]


 25%|██▌       | 8340/32777 [00:09<00:29, 827.09it/s]


 26%|██▌       | 8426/32777 [00:09<00:31, 778.88it/s]


 26%|██▌       | 8511/32777 [00:09<00:30, 792.68it/s]


 26%|██▌       | 8592/32777 [00:09<00:31, 779.07it/s]


 26%|██▋       | 8678/32777 [00:09<00:30, 793.27it/s]


 27%|██▋       | 8763/32777 [00:09<00:29, 805.84it/s]


 27%|██▋       | 8846/32777 [00:09<00:29, 809.89it/s]


 27%|██▋       | 8947/32777 [00:09<00:27, 859.98it/s]


 28%|██▊       | 9034/32777 [00:10<00:27, 862.08it/s]


 28%|██▊       | 9121/32777 [00:10<00:28, 838.45it/s]


 28%|██▊       | 9206/32777 [00:10<00:28, 836.56it/s]


 28%|██▊       | 9290/32777 [00:10<00:29, 798.22it/s]


 29%|██▊       | 9371/32777 [00:10<00:31, 753.74it/s]


 29%|██▉       | 9448/32777 [00:10<00:32, 725.24it/s]


 29%|██▉       | 9522/32777 [00:10<00:32, 723.94it/s]


 29%|██▉       | 9595/32777 [00:10<00:34, 669.72it/s]


 29%|██▉       | 9663/32777 [00:10<00:35, 656.27it/s]


 30%|██▉       | 9730/32777 [00:11<00:35, 652.16it/s]


 30%|██▉       | 9796/32777 [00:11<00:35, 639.01it/s]


 30%|███       | 9869/32777 [00:11<00:34, 664.41it/s]


 30%|███       | 9936/32777 [00:11<00:35, 648.23it/s]


 31%|███       | 10012/32777 [00:11<00:33, 676.12it/s]


 31%|███       | 10088/32777 [00:11<00:32, 691.84it/s]


 31%|███       | 10158/32777 [00:11<00:33, 682.59it/s]


 31%|███       | 10238/32777 [00:11<00:31, 712.61it/s]


 31%|███▏      | 10310/32777 [00:11<00:33, 667.60it/s]


 32%|███▏      | 10384/32777 [00:11<00:32, 680.55it/s]


 32%|███▏      | 10464/32777 [00:12<00:31, 712.58it/s]


 32%|███▏      | 10552/32777 [00:12<00:29, 758.63it/s]


 32%|███▏      | 10629/32777 [00:12<00:30, 733.70it/s]


 33%|███▎      | 10703/32777 [00:12<00:32, 685.63it/s]


 33%|███▎      | 10778/32777 [00:12<00:31, 697.54it/s]


 33%|███▎      | 10854/32777 [00:12<00:30, 713.85it/s]


 33%|███▎      | 10942/32777 [00:12<00:28, 760.28it/s]


 34%|███▎      | 11039/32777 [00:12<00:26, 820.35it/s]


 34%|███▍      | 11122/32777 [00:12<00:28, 757.60it/s]


 34%|███▍      | 11200/32777 [00:13<00:29, 725.19it/s]


 34%|███▍      | 11274/32777 [00:13<00:29, 724.26it/s]


 35%|███▍      | 11348/32777 [00:13<00:31, 680.54it/s]


 35%|███▍      | 11434/32777 [00:13<00:29, 727.39it/s]


 35%|███▌      | 11508/32777 [00:13<00:31, 677.04it/s]


 35%|███▌      | 11577/32777 [00:13<00:33, 627.10it/s]


 36%|███▌      | 11681/32777 [00:13<00:28, 731.63it/s]


 36%|███▌      | 11757/32777 [00:13<00:28, 735.03it/s]


 36%|███▌      | 11833/32777 [00:13<00:29, 721.88it/s]


 36%|███▋      | 11907/32777 [00:14<00:30, 676.57it/s]


 37%|███▋      | 11976/32777 [00:14<00:30, 674.31it/s]


 37%|███▋      | 12046/32777 [00:14<00:30, 680.35it/s]


 37%|███▋      | 12135/32777 [00:14<00:27, 739.56it/s]


 37%|███▋      | 12210/32777 [00:14<00:28, 712.60it/s]


 37%|███▋      | 12288/32777 [00:14<00:28, 722.05it/s]


 38%|███▊      | 12361/32777 [00:14<00:29, 699.89it/s]


 38%|███▊      | 12450/32777 [00:14<00:27, 748.93it/s]


 38%|███▊      | 12539/32777 [00:14<00:25, 788.26it/s]


 39%|███▊      | 12626/32777 [00:15<00:24, 810.53it/s]


 39%|███▉      | 12708/32777 [00:15<00:25, 777.08it/s]


 39%|███▉      | 12787/32777 [00:15<00:26, 760.34it/s]


 39%|███▉      | 12871/32777 [00:15<00:25, 781.23it/s]


 40%|███▉      | 12989/32777 [00:15<00:22, 895.97it/s]


 40%|███▉      | 13093/32777 [00:15<00:21, 931.08it/s]


 40%|████      | 13188/32777 [00:15<00:20, 935.47it/s]


 41%|████      | 13282/32777 [00:15<00:21, 886.28it/s]


 41%|████      | 13372/32777 [00:15<00:23, 813.18it/s]


 41%|████      | 13455/32777 [00:16<00:26, 738.74it/s]


 41%|████▏     | 13539/32777 [00:16<00:25, 759.79it/s]


 42%|████▏     | 13617/32777 [00:16<00:25, 751.93it/s]


 42%|████▏     | 13694/32777 [00:16<00:26, 718.82it/s]


 42%|████▏     | 13781/32777 [00:16<00:25, 757.58it/s]


 42%|████▏     | 13875/32777 [00:16<00:23, 807.53it/s]


 43%|████▎     | 13979/32777 [00:16<00:21, 867.39it/s]


 43%|████▎     | 14067/32777 [00:16<00:22, 818.53it/s]


 43%|████▎     | 14150/32777 [00:16<00:23, 803.71it/s]


 43%|████▎     | 14232/32777 [00:17<00:24, 769.81it/s]


 44%|████▎     | 14314/32777 [00:17<00:23, 782.11it/s]


 44%|████▍     | 14416/32777 [00:17<00:21, 847.82it/s]


 44%|████▍     | 14520/32777 [00:17<00:20, 882.78it/s]


 45%|████▍     | 14609/32777 [00:17<00:20, 879.34it/s]


 45%|████▍     | 14698/32777 [00:17<00:20, 862.28it/s]


 45%|████▌     | 14785/32777 [00:17<00:22, 807.86it/s]


 45%|████▌     | 14882/32777 [00:17<00:21, 849.39it/s]


 46%|████▌     | 14968/32777 [00:17<00:22, 775.09it/s]


 46%|████▌     | 15048/32777 [00:18<00:24, 720.42it/s]


 46%|████▌     | 15122/32777 [00:18<00:24, 719.91it/s]


 46%|████▋     | 15199/32777 [00:18<00:24, 730.88it/s]


 47%|████▋     | 15274/32777 [00:18<00:23, 734.93it/s]


 47%|████▋     | 15349/32777 [00:18<00:23, 733.42it/s]


 47%|████▋     | 15423/32777 [00:18<00:23, 728.96it/s]


 47%|████▋     | 15521/32777 [00:18<00:21, 797.66it/s]


 48%|████▊     | 15602/32777 [00:18<00:22, 766.63it/s]


 48%|████▊     | 15680/32777 [00:18<00:24, 709.13it/s]


 48%|████▊     | 15790/32777 [00:19<00:20, 814.06it/s]


 48%|████▊     | 15874/32777 [00:19<00:21, 780.71it/s]


 49%|████▊     | 15958/32777 [00:19<00:21, 790.11it/s]


 49%|████▉     | 16039/32777 [00:19<00:28, 580.23it/s]


 49%|████▉     | 16131/32777 [00:19<00:25, 655.29it/s]


 49%|████▉     | 16214/32777 [00:19<00:23, 697.05it/s]


 50%|████▉     | 16291/32777 [00:19<00:23, 696.39it/s]


 50%|████▉     | 16371/32777 [00:19<00:22, 723.67it/s]


 50%|█████     | 16448/32777 [00:20<00:23, 692.53it/s]


 50%|█████     | 16533/32777 [00:20<00:22, 733.82it/s]


 51%|█████     | 16626/32777 [00:20<00:20, 780.75it/s]


 51%|█████     | 16709/32777 [00:20<00:20, 794.12it/s]


 51%|█████     | 16790/32777 [00:20<00:20, 781.95it/s]


 52%|█████▏    | 16882/32777 [00:20<00:19, 817.78it/s]


 52%|█████▏    | 16975/32777 [00:20<00:18, 849.61it/s]


 52%|█████▏    | 17087/32777 [00:20<00:16, 923.13it/s]


 52%|█████▏    | 17180/32777 [00:20<00:17, 905.59it/s]


 53%|█████▎    | 17272/32777 [00:20<00:19, 795.00it/s]


 53%|█████▎    | 17355/32777 [00:21<00:19, 792.28it/s]


 53%|█████▎    | 17437/32777 [00:21<00:20, 747.22it/s]


 53%|█████▎    | 17514/32777 [00:21<00:20, 737.86it/s]


 54%|█████▎    | 17589/32777 [00:21<00:21, 716.99it/s]


 54%|█████▍    | 17662/32777 [00:21<00:22, 666.34it/s]


 54%|█████▍    | 17730/32777 [00:21<00:23, 649.18it/s]


 54%|█████▍    | 17796/32777 [00:21<00:23, 646.66it/s]


 55%|█████▍    | 17866/32777 [00:21<00:22, 659.77it/s]


 55%|█████▍    | 17951/32777 [00:21<00:20, 710.25it/s]


 55%|█████▌    | 18031/32777 [00:22<00:20, 731.03it/s]


 55%|█████▌    | 18105/32777 [00:22<00:21, 681.27it/s]


 55%|█████▌    | 18175/32777 [00:22<00:23, 633.92it/s]


 56%|█████▌    | 18256/32777 [00:22<00:21, 678.36it/s]


 56%|█████▌    | 18327/32777 [00:22<00:21, 679.47it/s]


 56%|█████▌    | 18396/32777 [00:22<00:21, 673.40it/s]


 56%|█████▋    | 18464/32777 [00:22<00:21, 672.04it/s]


 57%|█████▋    | 18548/32777 [00:22<00:19, 719.21it/s]


 57%|█████▋    | 18647/32777 [00:22<00:17, 792.35it/s]


 57%|█████▋    | 18727/32777 [00:23<00:18, 766.18it/s]


 57%|█████▋    | 18806/32777 [00:23<00:18, 771.46it/s]


 58%|█████▊    | 18884/32777 [00:23<00:18, 763.15it/s]


 58%|█████▊    | 18967/32777 [00:23<00:17, 775.30it/s]


 58%|█████▊    | 19045/32777 [00:23<00:18, 756.11it/s]


 58%|█████▊    | 19135/32777 [00:23<00:17, 792.62it/s]


 59%|█████▊    | 19219/32777 [00:23<00:16, 802.70it/s]


 59%|█████▉    | 19300/32777 [00:23<00:16, 797.59it/s]


 59%|█████▉    | 19380/32777 [00:23<00:16, 788.47it/s]


 59%|█████▉    | 19459/32777 [00:23<00:16, 787.93it/s]


 60%|█████▉    | 19538/32777 [00:24<00:16, 784.68it/s]


 60%|█████▉    | 19617/32777 [00:24<00:18, 724.23it/s]


 60%|██████    | 19711/32777 [00:24<00:16, 779.19it/s]


 60%|██████    | 19794/32777 [00:24<00:16, 782.50it/s]


 61%|██████    | 19873/32777 [00:24<00:16, 771.62it/s]


 61%|██████    | 19951/32777 [00:24<00:17, 748.14it/s]


 61%|██████    | 20027/32777 [00:24<00:17, 717.75it/s]


 61%|██████▏   | 20100/32777 [00:24<00:18, 677.92it/s]


 62%|██████▏   | 20202/32777 [00:24<00:16, 768.56it/s]


 62%|██████▏   | 20300/32777 [00:25<00:15, 815.84it/s]


 62%|██████▏   | 20383/32777 [00:25<00:15, 803.27it/s]


 62%|██████▏   | 20465/32777 [00:25<00:16, 751.29it/s]


 63%|██████▎   | 20553/32777 [00:25<00:15, 781.83it/s]


 63%|██████▎   | 20648/32777 [00:25<00:14, 819.78it/s]


 63%|██████▎   | 20759/32777 [00:25<00:13, 890.40it/s]


 64%|██████▎   | 20849/32777 [00:25<00:13, 860.71it/s]


 64%|██████▍   | 20936/32777 [00:25<00:15, 785.65it/s]


 64%|██████▍   | 21029/32777 [00:25<00:14, 817.24it/s]


 64%|██████▍   | 21113/32777 [00:26<00:14, 802.23it/s]


 65%|██████▍   | 21212/32777 [00:26<00:13, 847.79it/s]


 65%|██████▍   | 21298/32777 [00:26<00:13, 841.86it/s]


 65%|██████▌   | 21394/32777 [00:26<00:13, 869.31it/s]


 66%|██████▌   | 21511/32777 [00:26<00:11, 952.90it/s]


 66%|██████▌   | 21623/32777 [00:26<00:11, 999.30it/s]


 66%|██████▋   | 21724/32777 [00:26<00:11, 984.54it/s]


 67%|██████▋   | 21823/32777 [00:26<00:11, 930.78it/s]


 67%|██████▋   | 21917/32777 [00:26<00:13, 825.66it/s]


 67%|██████▋   | 22003/32777 [00:27<00:13, 825.26it/s]


 67%|██████▋   | 22088/32777 [00:27<00:12, 830.04it/s]


 68%|██████▊   | 22173/32777 [00:27<00:13, 806.98it/s]


 68%|██████▊   | 22255/32777 [00:27<00:13, 793.79it/s]


 68%|██████▊   | 22364/32777 [00:27<00:11, 876.52it/s]


 69%|██████▊   | 22453/32777 [00:27<00:12, 827.21it/s]


 69%|██████▉   | 22563/32777 [00:27<00:11, 896.46it/s]


 69%|██████▉   | 22660/32777 [00:27<00:11, 916.35it/s]


 69%|██████▉   | 22758/32777 [00:27<00:10, 934.23it/s]


 70%|██████▉   | 22869/32777 [00:28<00:10, 983.57it/s]


 70%|███████   | 22972/32777 [00:28<00:09, 989.50it/s]


 70%|███████   | 23074/32777 [00:28<00:09, 991.67it/s]


 71%|███████   | 23174/32777 [00:28<00:09, 988.64it/s]


 71%|███████   | 23274/32777 [00:28<00:10, 924.72it/s]


 71%|███████▏  | 23371/32777 [00:28<00:10, 935.29it/s]


 72%|███████▏  | 23466/32777 [00:28<00:10, 903.03it/s]


 72%|███████▏  | 23585/32777 [00:28<00:09, 969.85it/s]


 72%|███████▏  | 23683/32777 [00:28<00:09, 926.72it/s]


 73%|███████▎  | 23777/32777 [00:29<00:09, 902.78it/s]


 73%|███████▎  | 23892/32777 [00:29<00:09, 969.22it/s]


 73%|███████▎  | 23990/32777 [00:29<00:09, 926.42it/s]


 73%|███████▎  | 24084/32777 [00:29<00:09, 902.55it/s]


 74%|███████▍  | 24175/32777 [00:29<00:10, 833.81it/s]


 74%|███████▍  | 24263/32777 [00:29<00:10, 840.07it/s]


 74%|███████▍  | 24348/32777 [00:29<00:10, 827.77it/s]


 75%|███████▍  | 24445/32777 [00:29<00:09, 860.85it/s]


 75%|███████▍  | 24534/32777 [00:29<00:09, 865.64it/s]


 75%|███████▌  | 24634/32777 [00:29<00:09, 901.44it/s]


 75%|███████▌  | 24728/32777 [00:30<00:08, 911.32it/s]


 76%|███████▌  | 24820/32777 [00:30<00:08, 909.86it/s]


 76%|███████▌  | 24912/32777 [00:30<00:09, 860.41it/s]


 76%|███████▋  | 25005/32777 [00:30<00:08, 878.36it/s]


 77%|███████▋  | 25101/32777 [00:30<00:08, 898.25it/s]


 77%|███████▋  | 25227/32777 [00:30<00:07, 1000.13it/s]


 77%|███████▋  | 25341/32777 [00:30<00:07, 1036.05it/s]


 78%|███████▊  | 25446/32777 [00:30<00:07, 1011.23it/s]


 78%|███████▊  | 25569/32777 [00:30<00:06, 1073.24it/s]


 78%|███████▊  | 25677/32777 [00:31<00:07, 974.35it/s] 


 79%|███████▊  | 25777/32777 [00:31<00:07, 948.86it/s]


 79%|███████▉  | 25876/32777 [00:31<00:07, 958.53it/s]


 79%|███████▉  | 25973/32777 [00:31<00:07, 929.74it/s]


 80%|███████▉  | 26067/32777 [00:31<00:07, 852.34it/s]


 80%|███████▉  | 26187/32777 [00:31<00:06, 941.92it/s]


 80%|████████  | 26284/32777 [00:31<00:06, 941.54it/s]


 80%|████████  | 26380/32777 [00:31<00:06, 943.95it/s]


 81%|████████  | 26476/32777 [00:31<00:06, 918.81it/s]


 81%|████████  | 26571/32777 [00:32<00:06, 925.51it/s]


 81%|████████▏ | 26671/32777 [00:32<00:06, 942.58it/s]


 82%|████████▏ | 26766/32777 [00:32<00:06, 940.18it/s]


 82%|████████▏ | 26861/32777 [00:32<00:06, 915.54it/s]


 82%|████████▏ | 26958/32777 [00:32<00:06, 928.82it/s]


 83%|████████▎ | 27052/32777 [00:32<00:06, 896.16it/s]


 83%|████████▎ | 27142/32777 [00:32<00:06, 866.17it/s]


 83%|████████▎ | 27229/32777 [00:32<00:06, 836.29it/s]


 83%|████████▎ | 27315/32777 [00:32<00:06, 841.97it/s]


 84%|████████▎ | 27400/32777 [00:32<00:06, 837.89it/s]


 84%|████████▍ | 27484/32777 [00:33<00:06, 837.47it/s]


 84%|████████▍ | 27584/32777 [00:33<00:05, 877.94it/s]


 84%|████████▍ | 27684/32777 [00:33<00:05, 913.58it/s]


 85%|████████▍ | 27776/32777 [00:33<00:05, 906.34it/s]


 85%|████████▌ | 27882/32777 [00:33<00:05, 945.52it/s]


 85%|████████▌ | 27980/32777 [00:33<00:05, 954.88it/s]


 86%|████████▌ | 28094/32777 [00:33<00:04, 1009.59it/s]


 86%|████████▌ | 28196/32777 [00:33<00:05, 895.26it/s] 


 86%|████████▋ | 28288/32777 [00:33<00:05, 867.50it/s]


 87%|████████▋ | 28377/32777 [00:34<00:05, 783.87it/s]


 87%|████████▋ | 28461/32777 [00:34<00:05, 797.82it/s]


 87%|████████▋ | 28543/32777 [00:34<00:05, 795.60it/s]


 87%|████████▋ | 28630/32777 [00:34<00:05, 814.63it/s]


 88%|████████▊ | 28716/32777 [00:34<00:04, 823.31it/s]


 88%|████████▊ | 28800/32777 [00:34<00:04, 824.13it/s]


 88%|████████▊ | 28891/32777 [00:34<00:04, 848.95it/s]


 88%|████████▊ | 28977/32777 [00:34<00:04, 814.29it/s]


 89%|████████▊ | 29061/32777 [00:34<00:04, 814.19it/s]


 89%|████████▉ | 29173/32777 [00:35<00:04, 898.95it/s]


 89%|████████▉ | 29273/32777 [00:35<00:03, 925.81it/s]


 90%|████████▉ | 29367/32777 [00:35<00:03, 897.44it/s]


 90%|████████▉ | 29458/32777 [00:35<00:03, 870.10it/s]


 90%|█████████ | 29569/32777 [00:35<00:03, 938.12it/s]


 91%|█████████ | 29664/32777 [00:35<00:03, 923.99it/s]


 91%|█████████ | 29757/32777 [00:35<00:03, 881.05it/s]


 91%|█████████ | 29846/32777 [00:35<00:03, 850.85it/s]


 91%|█████████▏| 29939/32777 [00:35<00:03, 872.89it/s]


 92%|█████████▏| 30048/32777 [00:35<00:02, 931.26it/s]


 92%|█████████▏| 30146/32777 [00:36<00:02, 929.18it/s]


 92%|█████████▏| 30240/32777 [00:36<00:02, 894.09it/s]


 93%|█████████▎| 30358/32777 [00:36<00:02, 974.23it/s]


 93%|█████████▎| 30457/32777 [00:36<00:02, 913.96it/s]


 93%|█████████▎| 30550/32777 [00:36<00:02, 863.52it/s]


 93%|█████████▎| 30644/32777 [00:36<00:02, 882.30it/s]


 94%|█████████▍| 30756/32777 [00:36<00:02, 946.43it/s]


 94%|█████████▍| 30859/32777 [00:36<00:01, 965.46it/s]


 94%|█████████▍| 30957/32777 [00:36<00:01, 939.46it/s]


 95%|█████████▍| 31052/32777 [00:37<00:01, 919.65it/s]


 95%|█████████▌| 31148/32777 [00:37<00:01, 927.60it/s]


 95%|█████████▌| 31242/32777 [00:37<00:01, 927.92it/s]


 96%|█████████▌| 31344/32777 [00:37<00:01, 946.86it/s]


 96%|█████████▌| 31439/32777 [00:37<00:01, 937.32it/s]


 96%|█████████▋| 31566/32777 [00:37<00:01, 1031.01it/s]


 97%|█████████▋| 31670/32777 [00:37<00:01, 899.73it/s] 


 97%|█████████▋| 31771/32777 [00:37<00:01, 928.75it/s]


 97%|█████████▋| 31867/32777 [00:37<00:00, 913.63it/s]


 98%|█████████▊| 31961/32777 [00:38<00:00, 895.89it/s]


 98%|█████████▊| 32056/32777 [00:38<00:00, 903.47it/s]


 98%|█████████▊| 32148/32777 [00:38<00:00, 896.31it/s]


 98%|█████████▊| 32246/32777 [00:38<00:00, 910.95it/s]


 99%|█████████▊| 32356/32777 [00:38<00:00, 957.68it/s]


 99%|█████████▉| 32485/32777 [00:38<00:00, 1052.14it/s]


 99%|█████████▉| 32610/32777 [00:38<00:00, 1101.81it/s]


100%|█████████▉| 32721/32777 [00:38<00:00, 1060.15it/s]


100%|██████████| 32777/32777 [00:38<00:00, 843.76it/s] 



targets.shape: (64800,)
contexts.shape: (64800, 5)
labels.shape: (64800, 5)


### Configure the dataset for performance

To perform efficient batching for the potentially large number of training examples, use the `tf.data.Dataset` API. After this step, you would have a `tf.data.Dataset` object of `(target_word, context_word), (label)` elements to train your word2vec model!

In [27]:
BATCH_SIZE = 1024
BUFFER_SIZE = 10000
dataset = tf.data.Dataset.from_tensor_slices(((targets, contexts), labels))
dataset = dataset.shuffle(BUFFER_SIZE).batch(BATCH_SIZE, drop_remainder=True)
print(dataset)

<_BatchDataset element_spec=((TensorSpec(shape=(1024,), dtype=tf.int64, name=None), TensorSpec(shape=(1024, 5), dtype=tf.int64, name=None)), TensorSpec(shape=(1024, 5), dtype=tf.int64, name=None))>


Apply `Dataset.cache` and `Dataset.prefetch` to improve performance:

In [28]:
dataset = dataset.cache().prefetch(buffer_size=AUTOTUNE)
print(dataset)

<_PrefetchDataset element_spec=((TensorSpec(shape=(1024,), dtype=tf.int64, name=None), TensorSpec(shape=(1024, 5), dtype=tf.int64, name=None)), TensorSpec(shape=(1024, 5), dtype=tf.int64, name=None))>


## Model and training

The word2vec model can be implemented as a classifier to distinguish between true context words from skip-grams and false context words obtained through negative sampling. You can perform a dot product multiplication between the embeddings of target and context words to obtain predictions for labels and compute the loss function against true labels in the dataset.

### Subclassed word2vec model

Use the [Keras Subclassing API](https://www.tensorflow.org/guide/keras/custom_layers_and_models) to define your word2vec model with the following layers:

* `target_embedding`: A `tf.keras.layers.Embedding` layer, which looks up the embedding of a word when it appears as a target word. The number of parameters in this layer are `(vocab_size * embedding_dim)`.
* `context_embedding`: Another `tf.keras.layers.Embedding` layer, which looks up the embedding of a word when it appears as a context word. The number of parameters in this layer are the same as those in `target_embedding`, i.e. `(vocab_size * embedding_dim)`.
* `dots`: A `tf.keras.layers.Dot` layer that computes the dot product of target and context embeddings from a training pair.
* `flatten`: A `tf.keras.layers.Flatten` layer to flatten the results of `dots` layer into logits.

With the subclassed model, you can define the `call()` function that accepts `(target, context)` pairs which can then be passed into their corresponding embedding layer. Reshape the `context_embedding` to perform a dot product with `target_embedding` and return the flattened result.

Key point: The `target_embedding` and `context_embedding` layers can be shared as well. You could also use a concatenation of both embeddings as the final word2vec embedding.

In [29]:
class Word2Vec(tf.keras.Model):
  def __init__(self, vocab_size, embedding_dim):
    super(Word2Vec, self).__init__()
    self.target_embedding = layers.Embedding(vocab_size,
                                      embedding_dim,
                                      input_length=1,
                                      name="w2v_embedding")
    self.context_embedding = layers.Embedding(vocab_size,
                                       embedding_dim,
                                       input_length=num_ns+1)

  def call(self, pair):
    target, context = pair
    # target: (batch, dummy?)  # The dummy axis doesn't exist in TF2.7+
    # context: (batch, context)
    if len(target.shape) == 2:
      target = tf.squeeze(target, axis=1)
    # target: (batch,)
    word_emb = self.target_embedding(target)
    # word_emb: (batch, embed)
    context_emb = self.context_embedding(context)
    # context_emb: (batch, context, embed)
    dots = tf.einsum('be,bce->bc', word_emb, context_emb)
    # dots: (batch, context)
    return dots

### Define loss function and compile model


For simplicity, you can use `tf.keras.losses.CategoricalCrossEntropy` as an alternative to the negative sampling loss. If you would like to write your own custom loss function, you can also do so as follows:

``` python
def custom_loss(x_logit, y_true):
      return tf.nn.sigmoid_cross_entropy_with_logits(logits=x_logit, labels=y_true)
```

It's time to build your model! Instantiate your word2vec class with an embedding dimension of 128 (you could experiment with different values). Compile the model with the `tf.keras.optimizers.Adam` optimizer. 

In [30]:
embedding_dim = 128
word2vec = Word2Vec(vocab_size, embedding_dim)
word2vec.compile(optimizer='adam',
                 loss=tf.keras.losses.CategoricalCrossentropy(from_logits=True),
                 metrics=['accuracy'])

Also define a callback to log training statistics for TensorBoard:

In [31]:
tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir="logs")

Train the model on the `dataset` for some number of epochs:

In [32]:
word2vec.fit(dataset, epochs=20, callbacks=[tensorboard_callback])

Epoch 1/20



 1/63 [..............................] - ETA: 1:10 - loss: 1.6101 - accuracy: 0.1934

I0000 00:00:1701951621.205941   11367 device_compiler.h:186] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.



 2/63 [..............................] - ETA: 6s - loss: 1.6098 - accuracy: 0.1943  


 3/63 [>.............................] - ETA: 6s - loss: 1.6097 - accuracy: 0.1992


 4/63 [>.............................] - ETA: 5s - loss: 1.6097 - accuracy: 0.2026


 5/63 [=>............................] - ETA: 7s - loss: 1.6096 - accuracy: 0.1998


 6/63 [=>............................] - ETA: 7s - loss: 1.6095 - accuracy: 0.2017


 7/63 [==>...........................] - ETA: 7s - loss: 1.6095 - accuracy: 0.2017


 8/63 [==>...........................] - ETA: 6s - loss: 1.6094 - accuracy: 0.2041


 9/63 [===>..........................] - ETA: 6s - loss: 1.6094 - accuracy: 0.2045


10/63 [===>..........................] - ETA: 6s - loss: 1.6094 - accuracy: 0.2055


11/63 [====>.........................] - ETA: 6s - loss: 1.6093 - accuracy: 0.2054


12/63 [====>.........................] - ETA: 6s - loss: 1.6093 - accuracy: 0.2056


13/63 [=====>........................] - ETA: 6s - loss: 1.6093 - accuracy: 0.2055


14/63 [=====>........................] - ETA: 6s - loss: 1.6093 - accuracy: 0.2070


15/63 [======>.......................] - ETA: 5s - loss: 1.6092 - accuracy: 0.2072


16/63 [======>.......................] - ETA: 5s - loss: 1.6093 - accuracy: 0.2063


17/63 [=======>......................] - ETA: 5s - loss: 1.6093 - accuracy: 0.2067


18/63 [=======>......................] - ETA: 5s - loss: 1.6092 - accuracy: 0.2079


19/63 [========>.....................] - ETA: 5s - loss: 1.6092 - accuracy: 0.2100


20/63 [========>.....................] - ETA: 5s - loss: 1.6091 - accuracy: 0.2113


21/63 [=========>....................] - ETA: 4s - loss: 1.6091 - accuracy: 0.2115


22/63 [=========>....................] - ETA: 4s - loss: 1.6091 - accuracy: 0.2120


23/63 [=========>....................] - ETA: 4s - loss: 1.6091 - accuracy: 0.2120


25/63 [==========>...................] - ETA: 4s - loss: 1.6090 - accuracy: 0.2137


26/63 [===========>..................] - ETA: 4s - loss: 1.6090 - accuracy: 0.2145


27/63 [===========>..................] - ETA: 4s - loss: 1.6090 - accuracy: 0.2159


28/63 [============>.................] - ETA: 3s - loss: 1.6090 - accuracy: 0.2162


29/63 [============>.................] - ETA: 3s - loss: 1.6090 - accuracy: 0.2167


31/63 [=============>................] - ETA: 3s - loss: 1.6089 - accuracy: 0.2176


32/63 [==============>...............] - ETA: 3s - loss: 1.6089 - accuracy: 0.2183


33/63 [==============>...............] - ETA: 3s - loss: 1.6089 - accuracy: 0.2190


34/63 [===============>..............] - ETA: 3s - loss: 1.6089 - accuracy: 0.2204


35/63 [===============>..............] - ETA: 2s - loss: 1.6088 - accuracy: 0.2205


36/63 [================>.............] - ETA: 2s - loss: 1.6088 - accuracy: 0.2207


37/63 [================>.............] - ETA: 2s - loss: 1.6088 - accuracy: 0.2209


40/63 [==================>...........] - ETA: 2s - loss: 1.6088 - accuracy: 0.2222


44/63 [===================>..........] - ETA: 1s - loss: 1.6087 - accuracy: 0.2236


45/63 [====================>.........] - ETA: 1s - loss: 1.6087 - accuracy: 0.2242


46/63 [====================>.........] - ETA: 1s - loss: 1.6086 - accuracy: 0.2249


47/63 [=====================>........] - ETA: 1s - loss: 1.6086 - accuracy: 0.2255


49/63 [======================>.......] - ETA: 1s - loss: 1.6086 - accuracy: 0.2265


50/63 [======================>.......] - ETA: 1s - loss: 1.6085 - accuracy: 0.2266


51/63 [=======================>......] - ETA: 1s - loss: 1.6085 - accuracy: 0.2262


54/63 [========================>.....] - ETA: 0s - loss: 1.6085 - accuracy: 0.2271


56/63 [=========================>....] - ETA: 0s - loss: 1.6084 - accuracy: 0.2278


59/63 [===========================>..] - ETA: 0s - loss: 1.6083 - accuracy: 0.2300


60/63 [===========================>..] - ETA: 0s - loss: 1.6083 - accuracy: 0.2305


61/63 [============================>.] - ETA: 0s - loss: 1.6083 - accuracy: 0.2311


62/63 [============================>.] - ETA: 0s - loss: 1.6082 - accuracy: 0.2317


63/63 [==============================] - ETA: 0s - loss: 1.6082 - accuracy: 0.2319


63/63 [==============================] - 7s 93ms/step - loss: 1.6082 - accuracy: 0.2319


Epoch 2/20



 1/63 [..............................] - ETA: 0s - loss: 1.5907 - accuracy: 0.7295


19/63 [========>.....................] - ETA: 0s - loss: 1.5939 - accuracy: 0.5984


38/63 [=================>............] - ETA: 0s - loss: 1.5924 - accuracy: 0.5717


56/63 [=========================>....] - ETA: 0s - loss: 1.5902 - accuracy: 0.5576


63/63 [==============================] - 0s 3ms/step - loss: 1.5890 - accuracy: 0.5530


Epoch 3/20



 1/63 [..............................] - ETA: 0s - loss: 1.5585 - accuracy: 0.7451


19/63 [========>.....................] - ETA: 0s - loss: 1.5586 - accuracy: 0.6627


38/63 [=================>............] - ETA: 0s - loss: 1.5523 - accuracy: 0.6318


57/63 [==========================>...] - ETA: 0s - loss: 1.5448 - accuracy: 0.6144


63/63 [==============================] - 0s 3ms/step - loss: 1.5420 - accuracy: 0.6082


Epoch 4/20



 1/63 [..............................] - ETA: 0s - loss: 1.4866 - accuracy: 0.6504


20/63 [========>.....................] - ETA: 0s - loss: 1.4838 - accuracy: 0.6061


38/63 [=================>............] - ETA: 0s - loss: 1.4751 - accuracy: 0.5895


56/63 [=========================>....] - ETA: 0s - loss: 1.4650 - accuracy: 0.5828


63/63 [==============================] - 0s 3ms/step - loss: 1.4606 - accuracy: 0.5798


Epoch 5/20



 1/63 [..............................] - ETA: 0s - loss: 1.3869 - accuracy: 0.6143


20/63 [========>.....................] - ETA: 0s - loss: 1.3857 - accuracy: 0.5955


38/63 [=================>............] - ETA: 0s - loss: 1.3779 - accuracy: 0.5856


57/63 [==========================>...] - ETA: 0s - loss: 1.3672 - accuracy: 0.5856


63/63 [==============================] - 0s 3ms/step - loss: 1.3634 - accuracy: 0.5851


Epoch 6/20



 1/63 [..............................] - ETA: 0s - loss: 1.2828 - accuracy: 0.6230


20/63 [========>.....................] - ETA: 0s - loss: 1.2855 - accuracy: 0.6137


40/63 [==================>...........] - ETA: 0s - loss: 1.2788 - accuracy: 0.6070


59/63 [===========================>..] - ETA: 0s - loss: 1.2688 - accuracy: 0.6105


63/63 [==============================] - 0s 3ms/step - loss: 1.2667 - accuracy: 0.6103


Epoch 7/20



 1/63 [..............................] - ETA: 0s - loss: 1.1856 - accuracy: 0.6582


20/63 [========>.....................] - ETA: 0s - loss: 1.1916 - accuracy: 0.6459


39/63 [=================>............] - ETA: 0s - loss: 1.1868 - accuracy: 0.6415


58/63 [==========================>...] - ETA: 0s - loss: 1.1784 - accuracy: 0.6445


63/63 [==============================] - 0s 3ms/step - loss: 1.1758 - accuracy: 0.6449


Epoch 8/20



 1/63 [..............................] - ETA: 0s - loss: 1.0971 - accuracy: 0.6982


21/63 [=========>....................] - ETA: 0s - loss: 1.1048 - accuracy: 0.6783


41/63 [==================>...........] - ETA: 0s - loss: 1.1009 - accuracy: 0.6749


60/63 [===========================>..] - ETA: 0s - loss: 1.0923 - accuracy: 0.6794


63/63 [==============================] - 0s 3ms/step - loss: 1.0912 - accuracy: 0.6793


Epoch 9/20



 1/63 [..............................] - ETA: 0s - loss: 1.0163 - accuracy: 0.7227


21/63 [=========>....................] - ETA: 0s - loss: 1.0245 - accuracy: 0.7092


40/63 [==================>...........] - ETA: 0s - loss: 1.0211 - accuracy: 0.7070


60/63 [===========================>..] - ETA: 0s - loss: 1.0134 - accuracy: 0.7105


63/63 [==============================] - 0s 3ms/step - loss: 1.0125 - accuracy: 0.7105


Epoch 10/20



 1/63 [..............................] - ETA: 0s - loss: 0.9420 - accuracy: 0.7510


21/63 [=========>....................] - ETA: 0s - loss: 0.9501 - accuracy: 0.7391


40/63 [==================>...........] - ETA: 0s - loss: 0.9470 - accuracy: 0.7367


58/63 [==========================>...] - ETA: 0s - loss: 0.9411 - accuracy: 0.7388


63/63 [==============================] - 0s 3ms/step - loss: 0.9393 - accuracy: 0.7392


Epoch 11/20



 1/63 [..............................] - ETA: 0s - loss: 0.8735 - accuracy: 0.7783


21/63 [=========>....................] - ETA: 0s - loss: 0.8812 - accuracy: 0.7634


40/63 [==================>...........] - ETA: 0s - loss: 0.8783 - accuracy: 0.7626


59/63 [===========================>..] - ETA: 0s - loss: 0.8725 - accuracy: 0.7652


63/63 [==============================] - 0s 3ms/step - loss: 0.8715 - accuracy: 0.7653


Epoch 12/20



 1/63 [..............................] - ETA: 0s - loss: 0.8105 - accuracy: 0.7969


20/63 [========>.....................] - ETA: 0s - loss: 0.8179 - accuracy: 0.7864


39/63 [=================>............] - ETA: 0s - loss: 0.8146 - accuracy: 0.7865


58/63 [==========================>...] - ETA: 0s - loss: 0.8103 - accuracy: 0.7877


63/63 [==============================] - 0s 3ms/step - loss: 0.8089 - accuracy: 0.7878


Epoch 13/20



 1/63 [..............................] - ETA: 0s - loss: 0.7526 - accuracy: 0.8115


21/63 [=========>....................] - ETA: 0s - loss: 0.7592 - accuracy: 0.8065


41/63 [==================>...........] - ETA: 0s - loss: 0.7567 - accuracy: 0.8070


60/63 [===========================>..] - ETA: 0s - loss: 0.7517 - accuracy: 0.8083


63/63 [==============================] - 0s 3ms/step - loss: 0.7514 - accuracy: 0.8081


Epoch 14/20



 1/63 [..............................] - ETA: 0s - loss: 0.6995 - accuracy: 0.8330


20/63 [========>.....................] - ETA: 0s - loss: 0.7059 - accuracy: 0.8244


39/63 [=================>............] - ETA: 0s - loss: 0.7027 - accuracy: 0.8249


58/63 [==========================>...] - ETA: 0s - loss: 0.6996 - accuracy: 0.8253


63/63 [==============================] - 0s 3ms/step - loss: 0.6986 - accuracy: 0.8256


Epoch 15/20



 1/63 [..............................] - ETA: 0s - loss: 0.6511 - accuracy: 0.8477


20/63 [========>.....................] - ETA: 0s - loss: 0.6570 - accuracy: 0.8397


39/63 [=================>............] - ETA: 0s - loss: 0.6538 - accuracy: 0.8403


58/63 [==========================>...] - ETA: 0s - loss: 0.6513 - accuracy: 0.8406


63/63 [==============================] - 0s 3ms/step - loss: 0.6504 - accuracy: 0.8409


Epoch 16/20



 1/63 [..............................] - ETA: 0s - loss: 0.6069 - accuracy: 0.8613


20/63 [========>.....................] - ETA: 0s - loss: 0.6124 - accuracy: 0.8533


39/63 [=================>............] - ETA: 0s - loss: 0.6092 - accuracy: 0.8539


58/63 [==========================>...] - ETA: 0s - loss: 0.6072 - accuracy: 0.8543


63/63 [==============================] - 0s 3ms/step - loss: 0.6065 - accuracy: 0.8544


Epoch 17/20



 1/63 [..............................] - ETA: 0s - loss: 0.5668 - accuracy: 0.8770


20/63 [========>.....................] - ETA: 0s - loss: 0.5719 - accuracy: 0.8653


39/63 [=================>............] - ETA: 0s - loss: 0.5686 - accuracy: 0.8662


58/63 [==========================>...] - ETA: 0s - loss: 0.5671 - accuracy: 0.8667


63/63 [==============================] - 0s 3ms/step - loss: 0.5666 - accuracy: 0.8668


Epoch 18/20



 1/63 [..............................] - ETA: 0s - loss: 0.5303 - accuracy: 0.8838


20/63 [========>.....................] - ETA: 0s - loss: 0.5350 - accuracy: 0.8755


39/63 [=================>............] - ETA: 0s - loss: 0.5318 - accuracy: 0.8768


58/63 [==========================>...] - ETA: 0s - loss: 0.5306 - accuracy: 0.8775


63/63 [==============================] - 0s 3ms/step - loss: 0.5302 - accuracy: 0.8774


Epoch 19/20



 1/63 [..............................] - ETA: 0s - loss: 0.4971 - accuracy: 0.8965


21/63 [=========>....................] - ETA: 0s - loss: 0.5011 - accuracy: 0.8861


41/63 [==================>...........] - ETA: 0s - loss: 0.4990 - accuracy: 0.8863


60/63 [===========================>..] - ETA: 0s - loss: 0.4971 - accuracy: 0.8871


63/63 [==============================] - 0s 3ms/step - loss: 0.4972 - accuracy: 0.8868


Epoch 20/20



 1/63 [..............................] - ETA: 0s - loss: 0.4670 - accuracy: 0.9043


20/63 [========>.....................] - ETA: 0s - loss: 0.4712 - accuracy: 0.8940


38/63 [=================>............] - ETA: 0s - loss: 0.4678 - accuracy: 0.8959


58/63 [==========================>...] - ETA: 0s - loss: 0.4674 - accuracy: 0.8959


63/63 [==============================] - 0s 3ms/step - loss: 0.4672 - accuracy: 0.8956


TensorBoard now shows the word2vec model's accuracy and loss:

In [ ]:
#docs_infra: no_execute
%tensorboard --logdir logs

<!-- <img class="tfo-display-only-on-site" src="images/word2vec_tensorboard.png"/> -->

## Embedding lookup and analysis

Obtain the weights from the model using `Model.get_layer` and `Layer.get_weights`. The `TextVectorization.get_vocabulary` function provides the vocabulary to build a metadata file with one token per line.

In [33]:
weights = word2vec.get_layer('w2v_embedding').get_weights()[0]
vocab = vectorize_layer.get_vocabulary()

Create and save the vectors and metadata files:

In [34]:
out_v = io.open('vectors.tsv', 'w', encoding='utf-8')
out_m = io.open('metadata.tsv', 'w', encoding='utf-8')

for index, word in enumerate(vocab):
  if index == 0:
    continue  # skip 0, it's padding.
  vec = weights[index]
  out_v.write('\t'.join([str(x) for x in vec]) + "\n")
  out_m.write(word + "\n")
out_v.close()
out_m.close()

Download the `vectors.tsv` and `metadata.tsv` to analyze the obtained embeddings in the [Embedding Projector](https://projector.tensorflow.org/):

In [35]:
try:
  from google.colab import files
  files.download('vectors.tsv')
  files.download('metadata.tsv')
except Exception:
  pass

## Next steps


This tutorial has shown you how to implement a skip-gram word2vec model with negative sampling from scratch and visualize the obtained word embeddings.

* To learn more about word vectors and their mathematical representations, refer to these [notes](https://web.stanford.edu/class/cs224n/readings/cs224n-2019-notes01-wordvecs1.pdf).

* To learn more about advanced text processing, read the [Transformer model for language understanding](https://www.tensorflow.org/tutorials/text/transformer) tutorial.

* If you’re interested in pre-trained embedding models, you may also be interested in [Exploring the TF-Hub CORD-19 Swivel Embeddings](https://www.tensorflow.org/hub/tutorials/cord_19_embeddings_keras), or the [Multilingual Universal Sentence Encoder](https://www.tensorflow.org/hub/tutorials/cross_lingual_similarity_with_tf_hub_multilingual_universal_encoder).

* You may also like to train the model on a new dataset (there are many available in [TensorFlow Datasets](https://www.tensorflow.org/datasets)).
